server:
  port: 8000
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    #database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: ${CONFIG_MAIL_HOST}
    port: ${CONFIG_MAIL_PORT}
    smtp:
      auth: ${CONFIG_MAIL_SMTP_AUTH}
    starttls:
      enable: ${CONFIG_MAIL_STARTTLS}
    username: ${CONFIG_MAIL_USERNAME}
    password: ${CONFIG_MAIL_PASSWORD}
logging:
  level:
    com.bank: 'debug'
    org.springframework: 'error'
    org.hibernate: 'error'
schedule:
    cron: 0 0 0 * * *